name: Dev Build

on:
  push:
    branches:
      - '**' # every branch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle' # ðŸ”¥ built-in Gradle cache from setup-java

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Shorten commit SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Update mod_version
        run: sed -i "s/^mod_version=.*/mod_version=${SHORT_SHA}/" gradle.properties

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Upload built mod
        uses: actions/upload-artifact@v4
        with:
          name: devbuild-${{ github.sha }}
          path: |
            build/libs/*.jar
            !build/libs/*-sources.jar

      - name: Upload built sources
        uses: actions/upload-artifact@v4
        with:
          name: devbuild-sources-${{ github.sha }}
          path: build/libs/*-sources.jar
